version: '3.8'

services:

  redis-data:
    ports:
      - "6379:6379"
    # volumes:
    #   - airportsdistance-redisdata:/data

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
    ports:
      - "8002:80"
  
  ui:
    ports:
      - "3000:80"

volumes:
  airportsdistance-redisdata:
    external: false